language: csharp
solution: cloudscribe.SimpleContent.sln
sudo: false
dist: xenial
mono: none
dotnet: 3.0.100
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux

script:
  - dotnet restore
  - dotnet build -c Release
#  - dotnet test -c Release ./test/cloudscribe.SimpleContent.Web.Tests/cloudscribe.SimpleContent.Web.Tests.csproj


branches:
  only:
    - master



