image: Visual Studio 2017
environment:
  nodejs_version: "6.9.1"
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
init:
  - git config --global core.autocrlf true
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1
test: off

